# TEMPLATED
version: 2.1
workflows:
  version: 2
  build:
    jobs:
    - build-daffy-staging:
        context: pip-staging
        filters:
          branches:
            only: /daffy-staging.*/
    - build-daffy-prod:
        context: production
        filters:
          branches:
            ignore: /daffy-staging.*/
jobs:
  build: &build
    docker:
    - image: ${DOCKER_REGISTRY}/duckietown/aido-submission-ci-test:daffy-amd64
      auth:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD
    steps:
    - setup_remote_docker
    - checkout

    #    - run:
    #        name: Install dependencies
    #        command: |
    #          apt update && \
    #          apt install -y python3-pip git git-lfs curl && \
    #          rm -rf /var/lib/apt/lists/*
    #
    #    - run:
    #        name: Install Docker
    #        command: |
    #          curl -fsSL https://get.docker.com -o get-docker.sh
    #          sh get-docker.sh
    #          rm get-docker.sh
    #
    #    - run:
    #        name: Install dts
    #        command: |
    #          python3 -m pip install -U pip
    #          python3 -m pip check
    #          python3 -m pip install --no-cache-dir -U duckietown-shell
    #          python3 -m pip check
    #          export PATH="$PATH:$HOME/.local/bin"
    - run:
        name: Install dts commands
        command: |
          dts --debug --set-version "$DTS_VERSION" exit
    - run:
        name: config
        command: |
          dts --debug challenges config \
            --docker-server "$DOCKER_REGISTRY" \
            --docker-username "$DOCKER_USERNAME" \
            --docker-password "$DOCKER_PASSWORD"

    - run:
        name: Python stats
        command: |
          mkdir -p build-stats
          env | sort | tee  build-stats/env.txt
          pip list   | sort | tee  build-stats/pip-list.txt
          pip freeze | sort | tee  build-stats/pip-freeze.txt

    - store_artifacts:
        path: build-stats
        destination: build-stats

    - run:
        name: Pull the image
        command: |
          dts devel pull --tag daffy

    - run:
        name: Build the docs
        command: |
          dts devel docs build --tag daffy -f

    - store_artifacts:
        path: html
        destination: html

    - store_artifacts:
        path: html/package.tgz
        destination: out/package.tgz
  build-daffy-prod: *build
  build-daffy-staging: *build


