# these are the names of environment variables used to configure the connection to the matrix
ENV_VAR_CONTROLLER_CONNECT = "DT_MTX_CONNECT"
ENV_VAR_CONTROLLER_PROTOCOL = "DT_MTX_CONNECTOR_PROTOCOL"
ENV_VAR_CONTROLLER_HOSTNAME = "DT_MTX_CONNECTOR_HOST"
ENV_VAR_CONTROLLER_PORT = "DT_MTX_CONNECTOR_PORT"
ENV_VAR_AVATAR_NAME = "DT_MTX_AVATAR_NAME"

DEFAULT_MATRIX_CONTROLLER_DATA_CONNECTOR_PROTOCOL = "tcp"
DEFAULT_MATRIX_CONTROLLER_DATA_CONNECTOR_PORT = 7505
