# these are the names of environment variables used to configure the connection to the matrix
ENV_VAR_CONTROLLER_CONNECT = "DT_MTX_CONNECT"
ENV_VAR_CONTROLLER_PROTOCOL = "DT_MTX_CONNECTOR_PROTOCOL"
ENV_VAR_CONTROLLER_HOSTNAME = "DT_MTX_CONNECTOR_HOST"
ENV_VAR_CONTROLLER_PORT = "DT_MTX_CONNECTOR_PORT"

DEFAULT_MATRIX_CONTROLLER_DATA_CONNECTOR_PROTOCOL = "tcp"
DEFAULT_MATRIX_CONTROLLER_DATA_IN_CONNECTOR_PORT = 7505
DEFAULT_MATRIX_CONTROLLER_DATA_OUT_CONNECTOR_PORT = 7506
