#!/usr/bin/env python3

import os
import time

print("Running as UID:", os.getuid())

try:
    while True:
        time.sleep(1)
except KeyboardInterrupt:
    print("SIGINT received, exiting...")
    time.sleep(1)
    exit(0)
