# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WheelsCommandProto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WheelsCommandProto.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x18WheelsCommandProto.proto\"1\n\x12WheelsCommandProto\x12\x0c\n\x04left\x18\x01 \x01(\x02\x12\r\n\x05right\x18\x02 \x01(\x02\x62\x06proto3')
)




_WHEELSCOMMANDPROTO = _descriptor.Descriptor(
  name='WheelsCommandProto',
  full_name='WheelsCommandProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='left', full_name='WheelsCommandProto.left', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='right', full_name='WheelsCommandProto.right', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=77,
)

DESCRIPTOR.message_types_by_name['WheelsCommandProto'] = _WHEELSCOMMANDPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WheelsCommandProto = _reflection.GeneratedProtocolMessageType('WheelsCommandProto', (_message.Message,), dict(
  DESCRIPTOR = _WHEELSCOMMANDPROTO,
  __module__ = 'WheelsCommandProto_pb2'
  # @@protoc_insertion_point(class_scope:WheelsCommandProto)
  ))
_sym_db.RegisterMessage(WheelsCommandProto)


# @@protoc_insertion_point(module_scope)
