# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WorldMessageProto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CameraFrameProto_pb2 as CameraFrameProto__pb2
import TimeOfFlightRangeProto_pb2 as TimeOfFlightRangeProto__pb2
import WheelsCommandProto_pb2 as WheelsCommandProto__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WorldMessageProto.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x17WorldMessageProto.proto\x1a\x16\x43\x61meraFrameProto.proto\x1a\x1cTimeOfFlightRangeProto.proto\x1a\x18WheelsCommandProto.proto\"\xa6\x01\n\x11WorldMessageProto\x12)\n\x0c\x63\x61mera_frame\x18\x01 \x01(\x0b\x32\x11.CameraFrameProtoH\x00\x12,\n\ttof_range\x18\x02 \x01(\x0b\x32\x17.TimeOfFlightRangeProtoH\x00\x12-\n\x0ewheels_command\x18\x03 \x01(\x0b\x32\x13.WheelsCommandProtoH\x00\x42\t\n\x07messageb\x06proto3')
  ,
  dependencies=[CameraFrameProto__pb2.DESCRIPTOR,TimeOfFlightRangeProto__pb2.DESCRIPTOR,WheelsCommandProto__pb2.DESCRIPTOR,])




_WORLDMESSAGEPROTO = _descriptor.Descriptor(
  name='WorldMessageProto',
  full_name='WorldMessageProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='camera_frame', full_name='WorldMessageProto.camera_frame', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tof_range', full_name='WorldMessageProto.tof_range', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wheels_command', full_name='WorldMessageProto.wheels_command', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='message', full_name='WorldMessageProto.message',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=108,
  serialized_end=274,
)

_WORLDMESSAGEPROTO.fields_by_name['camera_frame'].message_type = CameraFrameProto__pb2._CAMERAFRAMEPROTO
_WORLDMESSAGEPROTO.fields_by_name['tof_range'].message_type = TimeOfFlightRangeProto__pb2._TIMEOFFLIGHTRANGEPROTO
_WORLDMESSAGEPROTO.fields_by_name['wheels_command'].message_type = WheelsCommandProto__pb2._WHEELSCOMMANDPROTO
_WORLDMESSAGEPROTO.oneofs_by_name['message'].fields.append(
  _WORLDMESSAGEPROTO.fields_by_name['camera_frame'])
_WORLDMESSAGEPROTO.fields_by_name['camera_frame'].containing_oneof = _WORLDMESSAGEPROTO.oneofs_by_name['message']
_WORLDMESSAGEPROTO.oneofs_by_name['message'].fields.append(
  _WORLDMESSAGEPROTO.fields_by_name['tof_range'])
_WORLDMESSAGEPROTO.fields_by_name['tof_range'].containing_oneof = _WORLDMESSAGEPROTO.oneofs_by_name['message']
_WORLDMESSAGEPROTO.oneofs_by_name['message'].fields.append(
  _WORLDMESSAGEPROTO.fields_by_name['wheels_command'])
_WORLDMESSAGEPROTO.fields_by_name['wheels_command'].containing_oneof = _WORLDMESSAGEPROTO.oneofs_by_name['message']
DESCRIPTOR.message_types_by_name['WorldMessageProto'] = _WORLDMESSAGEPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WorldMessageProto = _reflection.GeneratedProtocolMessageType('WorldMessageProto', (_message.Message,), dict(
  DESCRIPTOR = _WORLDMESSAGEPROTO,
  __module__ = 'WorldMessageProto_pb2'
  # @@protoc_insertion_point(class_scope:WorldMessageProto)
  ))
_sym_db.RegisterMessage(WorldMessageProto)


# @@protoc_insertion_point(module_scope)
